[theme]
primaryColor             = "#e05c52"
backgroundColor          = "#111827"
secondaryBackgroundColor = "#1e2736"
textColor                = "#c9d1d9"
font                     = "sans serif"

[server]
headless = true
